import React,{useContext,useEffect,useState}from'react';
import{AppBar,Avatar,CssBaseline,Divider,Drawer,Hidden,IconButton,List,ListItem,ListItemIcon,ListItemText,Menu,MenuItem,Toolbar,Tooltip,Typography}from'@material-ui/core';
import{AccountCircle,Assignment,Category,Dashboard,Home,People,QuestionAnswer,Settings}from'@material-ui/icons';
import MenuIcon from'@material-ui/icons/Menu';import{makeStyles}from'@material-ui/core/styles';
import UserContext from'../context/userContext';import NotificationBell from'../common/NotificationBell';
import SalesDashboard from'./SalesDashboard';import SalesMasterData from'./SalesMasterData';import SalesDocuments from'./SalesDocuments';import SalesSettings from'./SalesSettings';
const drawerWidth=250;
const useStyles=makeStyles(theme=>({root:{display:'flex'},appBar:{zIndex:theme.zIndex.drawer+1},appBarShift:{marginLeft:drawerWidth,width:`calc(100% - ${drawerWidth}px)`},drawerPaper:{width:drawerWidth,background:theme.palette.background.paper},toolbar:theme.mixins.toolbar,content:{flexGrow:1,minWidth:0,padding:theme.spacing(3),background:theme.palette.background.default,minHeight:'100vh'},contentShift:{marginLeft:drawerWidth},nav:{margin:'4px 12px',borderRadius:10,color:theme.palette.text.secondary,'& .MuiListItemIcon-root':{minWidth:40,color:theme.palette.text.secondary}},active:{background:'rgba(14,165,233,.14)',color:'#0284C7','& .MuiListItemIcon-root':{color:'#0EA5E9'},'& .MuiListItemText-primary':{fontWeight:700}},avatar:{width:34,height:34,background:'rgba(255,255,255,.25)'}}));
const pages={'/sales/dashboard':['Sales Dashboard',<Dashboard/>],'/sales/customers':['Customers',<People/>],'/sales/products':['Product Catalog',<Category/>],'/sales/inquiries':['Customer Inquiries',<QuestionAnswer/>],'/sales/orders':['Job Orders',<Assignment/>],'/sales/settings':['Workflow Settings',<Settings/>]};
export default function SalesModule({path,navigate,onExitModule}){const classes=useStyles(),{setUserData}=useContext(UserContext);const[mobile,setMobile]=useState(false),[drawer,setDrawer]=useState(true),[anchor,setAnchor]=useState(null),[user,setUser]=useState({});useEffect(()=>setUser(JSON.parse(sessionStorage.getItem('user'))||{}),[]);const page=pages[path]||pages['/sales/dashboard'];const go=to=>{navigate(to);if(window.innerWidth<960)setMobile(false)};const logout=()=>{sessionStorage.clear();setUserData({token:undefined,user:undefined})};const content=<><div className={classes.toolbar} style={{display:'grid',placeItems:'center'}}><img src="/unimore-logo-landscape.png" width="190" height="56" alt="" style={{objectFit:'contain'}}/></div><Divider/><Typography variant="caption" style={{padding:'16px 20px 4px',display:'block',color:'#9CA3AF',letterSpacing:1}}>SALES & JOB ORDERS</Typography><List>{Object.entries(pages).map(([route,item])=><ListItem button key={route} onClick={()=>go(route)} className={`${classes.nav} ${path===route?classes.active:''}`}><ListItemIcon>{item[1]}</ListItemIcon><ListItemText primary={item[0]}/></ListItem>)}</List></>;
return <div className={classes.root}><CssBaseline/><AppBar position="fixed" className={drawer?classes.appBarShift:classes.appBar}><Toolbar><IconButton color="inherit" edge="start" onClick={()=>window.innerWidth<960?setMobile(!mobile):setDrawer(!drawer)}><MenuIcon/></IconButton><Typography variant="h6" style={{flexGrow:1,marginLeft:12}}>{page[0]}</Typography><NotificationBell navigate={navigate}/><Tooltip title="Back to Modules"><IconButton color="inherit" onClick={onExitModule}><Home/></IconButton></Tooltip><IconButton color="inherit" onClick={e=>setAnchor(e.currentTarget)}><Avatar className={classes.avatar}>{user.Name?.charAt(0)||<AccountCircle/>}</Avatar><ListItemText style={{marginLeft:10}} primary={user.Name} secondary={<span style={{color:'rgba(255,255,255,.75)',fontSize:12}}>{user.role}</span>}/></IconButton><Menu anchorEl={anchor} open={Boolean(anchor)} onClose={()=>setAnchor(null)}><MenuItem onClick={logout}>Logout</MenuItem></Menu></Toolbar></AppBar><Hidden mdUp><Drawer variant="temporary" open={mobile} onClose={()=>setMobile(false)} classes={{paper:classes.drawerPaper}} ModalProps={{keepMounted:true}}>{content}</Drawer></Hidden><Hidden smDown><Drawer variant="persistent" open={drawer} classes={{paper:classes.drawerPaper}}>{content}</Drawer></Hidden><main className={`${classes.content} ${drawer?classes.contentShift:''}`}><div className={classes.toolbar}/>{path==='/sales/customers'?<SalesMasterData kind="customers"/>:path==='/sales/products'?<SalesMasterData kind="products"/>:path==='/sales/inquiries'?<SalesDocuments kind="inquiries"/>:path==='/sales/orders'?<SalesDocuments kind="orders"/>:path==='/sales/settings'?<SalesSettings/>:<SalesDashboard navigate={navigate}/>}</main></div>}
