import React,{useCallback,useEffect,useMemo,useState} from 'react';
import {Button,Card,CardContent,Chip,Dialog,DialogActions,DialogContent,DialogTitle,Grid,IconButton,MenuItem,Snackbar,Table,TableBody,TableCell,TableContainer,TableHead,TableRow,TextField,Tooltip,Typography} from '@material-ui/core';
import {Add,Delete,Edit,Refresh} from '@material-ui/icons';
import {Alert} from '@material-ui/lab';
import axios from 'axios'; import moment from 'moment';
const chipColor=value=>['Passed','Verified','Closed','Active'].includes(value)?'primary':['Rejected','Critical','Cancelled','Inactive'].includes(value)?'secondary':'default';
export default function QARecordBoard({resource,title,subtitle,fields,columns}){
 const empty=useMemo(()=>fields.reduce((a,f)=>({...a,[f.name]:f.defaultValue!==undefined?f.defaultValue:''}),{}),[fields]);
 const [rows,setRows]=useState([]),[relations,setRelations]=useState({}),[batches,setBatches]=useState([]),[form,setForm]=useState(empty),[editing,setEditing]=useState(null),[open,setOpen]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(null);
 const endpoint=window.apihost+`quality/${resource}`;
 const load=useCallback(()=>axios.get(endpoint).then(r=>setRows(Array.isArray(r.data)?r.data:[])).catch(e=>setMessage({type:'error',text:e.response?.data?.message||'Unable to load quality records.'})),[endpoint]);
 const loadBatches=useCallback(()=>{if(resource==='inspections')return axios.get(window.apihost+'quality/production-batches').then(r=>setBatches((r.data||[]).filter(b=>b.QAStatus==='Pending Inspection'))).catch(()=>{});},[resource]);
 useEffect(load,[load]);
 useEffect(()=>{fields.filter(f=>f.type==='relation').forEach(f=>axios.get(window.apihost+f.endpoint).then(r=>setRelations(current=>({...current,[f.name]:r.data||[]}))).catch(()=>{}));},[fields]);
 useEffect(()=>{loadBatches();},[loadBatches]);
 const show=(row,preset={})=>{setEditing(row||null);setForm(row?fields.reduce((a,f)=>({...a,[f.name]:f.type==='date'&&row[f.name]?moment(row[f.name]).format('YYYY-MM-DD'):(row[f.name]??'')}),{}):{...empty,...preset});setOpen(true);};
 const save=async e=>{e.preventDefault();setBusy(true);try{editing?await axios.put(`${endpoint}/${editing.Id}`,form):await axios.post(endpoint,form);setOpen(false);setMessage({type:'success',text:`${title} saved.`});load();loadBatches();}catch(error){setMessage({type:'error',text:error.response?.data?.message||'Unable to save record.'});}finally{setBusy(false);}};
 const remove=async row=>{if(!window.confirm(`Remove ${title.toLowerCase()} #${row.Id}?`))return;try{await axios.delete(`${endpoint}/${row.Id}`);load();}catch(error){setMessage({type:'error',text:error.response?.data?.message||'Unable to remove record.'});}};
 const display=(row,col)=>{const v=row[col.name];if(col.type==='date')return v?moment(v).format('MMM D, YYYY'):'—';if(col.type==='status')return <Chip size="small" label={v||'—'} color={chipColor(v)}/>;if(col.type==='active')return <Chip size="small" label={v?'Active':'Inactive'} color={v?'primary':'default'}/>;if(col.type==='evidence')return v?<Chip size="small" label="Photo attached" color="primary"/>:'—';return v??'—';};
 const imageChange=(field,file)=>{if(!file)return;if(file.size>2500000){setMessage({type:'error',text:'Evidence image must be 2.5 MB or smaller.'});return;}const reader=new FileReader();reader.onload=()=>setForm(current=>({...current,[field]:reader.result}));reader.readAsDataURL(file);};
 const options=f=>(f.options||[]).map(option=>typeof option==='object'?option:{label:option,value:option});
 return <div><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:16,flexWrap:'wrap',marginBottom:18}}><div><Typography variant="h5" style={{fontWeight:700}}>{title}</Typography><Typography color="textSecondary">{subtitle}</Typography></div><div><Tooltip title="Refresh"><IconButton onClick={load}><Refresh/></IconButton></Tooltip><Button variant="contained" color="primary" startIcon={<Add/>} onClick={()=>show(null)}>Add {title}</Button></div></div>
 {resource==='inspections'&&batches.length>0&&<Card style={{marginBottom:16,borderLeft:'4px solid #F59E0B'}}><CardContent><Typography variant="subtitle1" style={{fontWeight:700}}>Production batches awaiting inspection</Typography><Typography variant="body2" color="textSecondary" style={{marginBottom:10}}>Select a batch to prepare its QA inspection record.</Typography><div style={{display:'flex',gap:8,flexWrap:'wrap'}}>{batches.map(batch=><Chip key={batch.Id} clickable color="primary" variant="outlined" label={`${batch.BatchNo} — ${batch.FinishedProduct||'Production Batch'}`} onClick={()=>show(null,{InspectionType:'Production',ReferenceType:'Production Batch',ReferenceNo:batch.BatchNo,ProductName:batch.FinishedProduct||'',Quantity:batch.Quantity||'',InspectionDate:moment().format('YYYY-MM-DD'),Result:'Pending'})}/>)}</div></CardContent></Card>}
 <Card><CardContent style={{padding:0}}><TableContainer style={{maxHeight:'calc(100vh - 220px)'}}><Table stickyHeader size="small"><TableHead><TableRow>{columns.map(c=><TableCell key={c.name} style={{fontWeight:700,minWidth:c.width,whiteSpace:'nowrap'}}>{c.label}</TableCell>)}<TableCell align="right">Actions</TableCell></TableRow></TableHead><TableBody>{!rows.length&&<TableRow><TableCell colSpan={columns.length+1} align="center" style={{padding:40}}>No records yet.</TableCell></TableRow>}{rows.map(row=><TableRow hover key={row.Id}>{columns.map(c=><TableCell key={c.name}>{display(row,c)}</TableCell>)}<TableCell align="right" style={{whiteSpace:'nowrap'}}><IconButton size="small" onClick={()=>show(row)}><Edit fontSize="small"/></IconButton><IconButton size="small" onClick={()=>remove(row)}><Delete fontSize="small"/></IconButton></TableCell></TableRow>)}</TableBody></Table></TableContainer></CardContent></Card>
 <Dialog open={open} onClose={()=>!busy&&setOpen(false)} fullWidth maxWidth="md"><form onSubmit={save}><DialogTitle>{editing?'Edit':'Add'} {title}</DialogTitle><DialogContent><Grid container spacing={2}>{fields.map(f=><Grid item xs={12} sm={f.type==='multiline'||f.type==='image'?12:6} key={f.name}>{f.type==='relation'?<TextField select fullWidth margin="dense" variant="outlined" label={f.label} value={form[f.name]} onChange={e=>setForm({...form,[f.name]:e.target.value})}><MenuItem value="">None</MenuItem>{(relations[f.name]||[]).map(item=><MenuItem key={item[f.valueKey]} value={item[f.valueKey]}>{f.labelKeys.map(k=>item[k]).filter(Boolean).join(' — ')}</MenuItem>)}</TextField>:f.type==='image'?<div style={{border:'1px solid var(--app-border)',borderRadius:8,padding:12,marginTop:8}}><Typography variant="body2" style={{fontWeight:600,marginBottom:8}}>{f.label}</Typography><input type="file" accept="image/*" onChange={e=>imageChange(f.name,e.target.files[0])}/>{form[f.name]&&<div style={{marginTop:10,display:'flex',alignItems:'center',gap:10}}><img src={form[f.name]} alt="Defect evidence" style={{width:90,height:70,objectFit:'cover',borderRadius:6}}/><Button size="small" color="secondary" onClick={()=>setForm({...form,[f.name]:''})}>Remove</Button></div>}</div>:<TextField select={f.type==='select'} fullWidth margin="dense" variant="outlined" required={f.required} multiline={f.type==='multiline'} rows={f.type==='multiline'?3:undefined} type={['date','number'].includes(f.type)?f.type:'text'} label={f.label} value={form[f.name]} onChange={e=>setForm({...form,[f.name]:f.type==='number'&&e.target.value!==''?Number(e.target.value):e.target.value})} InputLabelProps={f.type==='date'?{shrink:true}:undefined}>{f.type==='select'&&options(f).map(o=><MenuItem key={String(o.value)} value={o.value}>{o.label}</MenuItem>)}</TextField>}</Grid>)}</Grid></DialogContent><DialogActions><Button onClick={()=>setOpen(false)} disabled={busy}>Cancel</Button><Button type="submit" variant="contained" color="primary" disabled={busy}>{busy?'Saving…':'Save'}</Button></DialogActions></form></Dialog>
 <Snackbar open={Boolean(message)} autoHideDuration={5000} onClose={()=>setMessage(null)}><Alert severity={message?.type||'info'} onClose={()=>setMessage(null)}>{message?.text}</Alert></Snackbar></div>;
}
