import React, { useEffect, useState } from 'react';
import { Card, CardContent, Chip, CircularProgress, Grid, Table, TableBody, TableCell, TableContainer, TableHead, TableRow, Typography } from '@material-ui/core';
import { Build, Computer, Devices, Storage, Security } from '@material-ui/icons';
import axios from 'axios';
import moment from 'moment';

const Metric = ({ label, value, icon, color }) => <Card style={{ height: '100%' }}><CardContent style={{ display: 'flex', gap: 14, alignItems: 'center' }}><div style={{ width: 44, height: 44, borderRadius: 12, display: 'grid', placeItems: 'center', color, background: `${color}22` }}>{icon}</div><div><Typography variant="h4" style={{ fontWeight: 700 }}>{value || 0}</Typography><Typography color="textSecondary">{label}</Typography></div></CardContent></Card>;
export default function ITDashboard() {
    const [data, setData] = useState(null); const [error, setError] = useState('');
    useEffect(() => { axios.get(window.apihost + 'it-assets/dashboard').then(r => setData(r.data)).catch(e => setError(e.response?.data?.message || 'Unable to load IT dashboard.')); }, []);
    if (error) return <Typography color="error">{error}</Typography>; if (!data) return <div style={{ display: 'grid', placeItems: 'center', minHeight: 300 }}><CircularProgress /></div>;
    const s = data.summary || {};
    return <div><Typography variant="h5" style={{ fontWeight: 700 }}>IT Operations Overview</Typography><Typography color="textSecondary" style={{ marginBottom: 18 }}>Asset deployment, stock, repairs and warranty visibility.</Typography><Grid container spacing={2}>{[
        ['Total Assets',s.TotalAssets,<Devices />,'#2563EB'],['Deployed',s.Deployed,<Computer />,'#10B981'],['In Stock',s.InStock,<Storage />,'#06B6D4'],['Under Repair',s.UnderRepair,<Build />,'#EF4444'],['Warranty Expiring',s.WarrantyExpiring,<Security />,'#F59E0B']
    ].map(([l,v,i,c]) => <Grid item xs={12} sm={6} lg key={l}><Metric label={l} value={v} icon={i} color={c} /></Grid>)}</Grid><Grid container spacing={2} style={{ marginTop: 4 }}><Grid item xs={12} md={5}><Card style={{ height: '100%' }}><CardContent><Typography variant="h6" style={{ fontWeight: 700 }}>Assets by Category</Typography>{!data.categories.length && <Typography color="textSecondary" style={{ marginTop: 20 }}>No assets registered yet.</Typography>}{data.categories.map(row => <div key={row.Category} style={{ display: 'flex', justifyContent: 'space-between', padding: '10px 0', borderBottom: '1px solid var(--app-border)' }}><span>{row.Category}</span><Chip size="small" label={row.AssetCount} /></div>)}</CardContent></Card></Grid><Grid item xs={12} md={7}><Card><CardContent style={{ padding: 0 }}><Typography variant="h6" style={{ fontWeight: 700, padding: 16 }}>Needs Attention</Typography><TableContainer><Table size="small"><TableHead><TableRow><TableCell>Asset</TableCell><TableCell>Category</TableCell><TableCell>Status</TableCell><TableCell>Warranty</TableCell></TableRow></TableHead><TableBody>{!data.attention.length && <TableRow><TableCell colSpan={4} align="center" style={{ padding: 30 }}>No repair or warranty issues.</TableCell></TableRow>}{data.attention.map(row => <TableRow key={row.Id}><TableCell><b>{row.AssetTag}</b><br />{[row.Brand,row.Model].filter(Boolean).join(' ')}</TableCell><TableCell>{row.Category}</TableCell><TableCell><Chip size="small" label={row.Status} /></TableCell><TableCell>{row.WarrantyExpiry ? moment(row.WarrantyExpiry).format('MMM D, YYYY') : '—'}</TableCell></TableRow>)}</TableBody></Table></TableContainer></CardContent></Card></Grid></Grid></div>;
}
