import React, { useCallback, useEffect, useMemo, useState } from 'react';
import { Button, Chip, CircularProgress, Dialog, DialogActions, DialogContent, DialogTitle, Grid, IconButton, InputAdornment, MenuItem, Paper, Table, TableBody, TableCell, TableContainer, TableHead, TableRow, TextField, Tooltip, Typography } from '@material-ui/core';
import { Autocomplete, Alert } from '@material-ui/lab';
import { Edit, PersonAdd, Refresh, Search } from '@material-ui/icons';
import { ToastContainer, toast } from 'react-toastify';
import axios from 'axios';
import moment from 'moment';
import EmployeeAvatar from '../common/EmployeeAvatar';
import { apiMessage, employeeName, money, today } from './utils';

export default function UteslaMembers() {
    const [members,setMembers]=useState([]),[employees,setEmployees]=useState([]),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[search,setSearch]=useState(''),[open,setOpen]=useState(false),[edit,setEdit]=useState(null);
    const [form,setForm]=useState({employee:null,MemberNo:'',JoinedDate:today(),MonthlyContribution:'',Status:'Active',Notes:''});
    const load=useCallback(()=>{setLoading(true);Promise.all([axios.get(window.apihost+'utesla/members'),axios.get(window.apihost+'utesla/employee-options')]).then(([m,e])=>{setMembers(m.data||[]);setEmployees(e.data||[])}).catch(error=>toast.error(apiMessage(error),{position:'top-center'})).finally(()=>setLoading(false))},[]);
    useEffect(load,[load]);
    const rows=useMemo(()=>members.filter(row=>!search||[employeeName(row),row.MemberNo,row.EmployeeNo,row.Department].join(' ').toLowerCase().includes(search.toLowerCase())),[members,search]);
    const add=()=>{setEdit(null);setForm({employee:null,MemberNo:'',JoinedDate:today(),MonthlyContribution:'',Status:'Active',Notes:''});setOpen(true)};
    const editMember=row=>{setEdit(row);setForm({employee:null,MemberNo:row.MemberNo,JoinedDate:moment(row.JoinedDate).format('YYYY-MM-DD'),MonthlyContribution:row.MonthlyContribution,Status:row.Status,Notes:row.Notes||''});setOpen(true)};
    const save=async()=>{if(!edit&&!form.employee)return toast.error('Select an employee.',{position:'top-center'});setSaving(true);try{if(edit)await axios.put(window.apihost+`utesla/members/${edit.Id}`,form);else await axios.post(window.apihost+'utesla/members',{EmployeeId:form.employee.id,MemberNo:form.MemberNo,JoinedDate:form.JoinedDate,MonthlyContribution:form.MonthlyContribution,Notes:form.Notes});toast.success(edit?'Membership updated.':'Employee registered as a UTESLA member.',{position:'top-center'});setOpen(false);load()}catch(error){toast.error(apiMessage(error),{position:'top-center'})}finally{setSaving(false)}};
    return <Paper elevation={0} style={{padding:24,borderRadius:14}}><ToastContainer/><Grid container spacing={2} alignItems="center" style={{marginBottom:18}}><Grid item><div><Typography variant="h6">UTESLA Membership</Typography><Typography variant="body2" color="textSecondary">One membership record per active employee, with a complete financial history.</Typography></div></Grid><Grid item xs/><Grid item xs={12} sm="auto"><TextField size="small" variant="outlined" placeholder="Search members" value={search} onChange={e=>setSearch(e.target.value)} InputProps={{startAdornment:<InputAdornment position="start"><Search fontSize="small"/></InputAdornment>}}/></Grid><Grid item><Tooltip title="Refresh"><IconButton onClick={load}><Refresh/></IconButton></Tooltip></Grid><Grid item><Button color="primary" variant="contained" startIcon={<PersonAdd/>} onClick={add}>Register Member</Button></Grid></Grid>
        <Alert severity="info" style={{marginBottom:16}}>Membership is stored separately from the employee table so suspension, exit dates, savings, loans, and future re-enrollment can be audited without changing HR identity data.</Alert>
        <TableContainer><Table><TableHead><TableRow><TableCell>Member</TableCell><TableCell>Department</TableCell><TableCell>Joined</TableCell><TableCell>Status</TableCell><TableCell align="right">Monthly contribution</TableCell><TableCell align="right">Savings</TableCell><TableCell align="right">Active loan balance</TableCell><TableCell align="right">Action</TableCell></TableRow></TableHead><TableBody>
            {loading&&<TableRow><TableCell colSpan={8} align="center" style={{padding:50}}><CircularProgress size={28}/></TableCell></TableRow>}
            {!loading&&rows.map(row=><TableRow hover key={row.Id}><TableCell><div style={{display:'flex',alignItems:'center',gap:10}}><EmployeeAvatar image={row.Image} name={employeeName(row)}/><div><strong>{employeeName(row)}</strong><br/><Typography variant="caption" color="textSecondary">{row.MemberNo} · Employee {row.EmployeeNo}</Typography></div></div></TableCell><TableCell>{row.Department||'—'}</TableCell><TableCell>{moment(row.JoinedDate).format('MMM D, YYYY')}</TableCell><TableCell><Chip size="small" label={row.Status} color={row.Status==='Active'?'primary':'default'}/></TableCell><TableCell align="right">{money(row.MonthlyContribution)}</TableCell><TableCell align="right">{money(row.SavingsBalance)}</TableCell><TableCell align="right">{money(row.ActiveLoanBalance)}</TableCell><TableCell align="right"><Tooltip title="Edit membership"><IconButton size="small" onClick={()=>editMember(row)}><Edit fontSize="small"/></IconButton></Tooltip></TableCell></TableRow>)}
            {!loading&&!rows.length&&<TableRow><TableCell colSpan={8} align="center" style={{padding:45}}><Typography color="textSecondary">No UTESLA members found.</Typography></TableCell></TableRow>}
        </TableBody></Table></TableContainer>
        <Dialog open={open} onClose={()=>!saving&&setOpen(false)} fullWidth maxWidth="sm"><DialogTitle>{edit?'Edit Membership':'Register UTESLA Member'}</DialogTitle><DialogContent>
            {!edit&&<Autocomplete options={employees} value={form.employee} onChange={(_e,value)=>setForm({...form,employee:value})} getOptionLabel={option=>`${option.employeeNo} - ${option.employeeName}`} getOptionSelected={(option,value)=>option.id===value.id} renderOption={option=><div style={{display:'flex',alignItems:'center',gap:10}}><EmployeeAvatar image={option.image} name={option.employeeName} size={32}/><div>{option.employeeName}<br/><Typography variant="caption" color="textSecondary">{option.employeeNo} · {option.department||'No department'}</Typography></div></div>} renderInput={params=><TextField {...params} label="Employee" variant="outlined" margin="normal" required/>}/>} 
            <Grid container spacing={2}><Grid item xs={12} sm={6}><TextField fullWidth variant="outlined" margin="normal" label="Member number (optional)" disabled={Boolean(edit)} value={form.MemberNo} onChange={e=>setForm({...form,MemberNo:e.target.value})} helperText="Leave blank to generate automatically."/></Grid><Grid item xs={12} sm={6}><TextField fullWidth variant="outlined" margin="normal" label="Joined date" type="date" InputLabelProps={{shrink:true}} disabled={Boolean(edit)} value={form.JoinedDate} onChange={e=>setForm({...form,JoinedDate:e.target.value})}/></Grid><Grid item xs={12} sm={6}><TextField fullWidth variant="outlined" label="Monthly contribution" type="number" inputProps={{min:0,step:'0.01'}} value={form.MonthlyContribution} onChange={e=>setForm({...form,MonthlyContribution:e.target.value})}/></Grid>{edit&&<Grid item xs={12} sm={6}><TextField select fullWidth variant="outlined" label="Membership status" value={form.Status} onChange={e=>setForm({...form,Status:e.target.value})}>{['Active','Suspended','Exited'].map(status=><MenuItem key={status} value={status}>{status}</MenuItem>)}</TextField></Grid>}<Grid item xs={12}><TextField fullWidth multiline rows={3} variant="outlined" label="Notes" value={form.Notes} onChange={e=>setForm({...form,Notes:e.target.value})}/></Grid></Grid>
        </DialogContent><DialogActions><Button disabled={saving} onClick={()=>setOpen(false)}>Cancel</Button><Button disabled={saving} color="primary" variant="contained" onClick={save}>{saving?<CircularProgress size={22}/>:edit?'Save Changes':'Register Member'}</Button></DialogActions></Dialog>
    </Paper>;
}
