const coilModel = require("../../models/production/coilModel");
const statuses = ["Unprocessed", "Partial Processed", "Fully Processed", "Reject"];
const text = (value) => value == null ? "" : String(value).trim();
const number = (value) => Number.isFinite(Number(value)) ? Number(value) : 0;
const date = (value, fallback = null) => { if (!value) return fallback; const parsed = new Date(value); return Number.isNaN(parsed.getTime()) ? fallback : parsed; };
const normalize = (body = {}) => ({
    SkelpNo:text(body.SkelpNo ?? body.skelpNo), SlitFormNo:text(body.SlitFormNo ?? body.slitFormNo), Date:date(body.Date ?? body.date,new Date()),
    ProdFormNo:text(body.ProdFormNo ?? body.prodFormNo), HSPrime:text(body.HSPrime ?? body.hsPrime), Thickness:number(body.Thickness ?? body.thickness), Width:number(body.Width ?? body.width), Weight:number(body.Weight ?? body.weight), WeightBefProc:number(body.WeightBefProc ?? body.weightBefProc), FGtoProduce:text(body.FGtoProduce ?? body.fgToProduce), LengthofFg:number(body.LengthofFg ?? body.lengthOfFg), Remarks:text(body.Remarks ?? body.remarks), Status:statuses.includes(body.Status ?? body.status)?(body.Status ?? body.status):"Unprocessed", DateProcessed:date(body.DateProcessed ?? body.dateProcessed,null), Operator:text(body.Operator ?? body.operator), OtherRemarks:text(body.OtherRemarks ?? body.otherRemarks), Location:text(body.Location ?? body.location),
});
const round = (value) => Number.isFinite(value) ? Number(value.toFixed(2)) : 0;
const shape = (row) => { const length=row.Thickness&&row.Width?row.Weight/(row.Thickness*row.Width*7.85*.000001)/1000:0; return { id:String(row.Id),skelpNo:row.SkelpNo,slitFormNo:row.SlitFormNo||"",date:row.Date,prodFormNo:row.ProdFormNo||"",hsPrime:row.HSPrime||"",thickness:row.Thickness||0,width:row.Width||0,weight:row.Weight||0,weightMT:round((row.Weight||0)/1000),weightBefProc:row.WeightBefProc||0,estLength:round(length),estQtyProduce:round(row.LengthofFg?length/(row.LengthofFg/1000):0),fgToProduce:row.FGtoProduce||"",lengthOfFg:row.LengthofFg||0,remarks:row.Remarks||"",status:row.Status||"Unprocessed",dateProcessed:row.DateProcessed,operator:row.Operator||"",otherRemarks:row.OtherRemarks||"",location:row.Location||""}; };
const validate = (item) => !item.SkelpNo ? "Coil No. is required." : [item.Thickness,item.Width,item.Weight,item.WeightBefProc,item.LengthofFg].some(v=>v<0) ? "Numeric inventory values cannot be negative." : null;
const list = async(_q,r)=>{try{r.json((await coilModel.list()).map(shape));}catch(e){r.status(500).json({error:e.message});}};
const get = async(q,r)=>{try{const row=await coilModel.findById(q.params.id);if(!row)return r.status(404).json({error:"Coil not found."});r.json(shape(row));}catch(e){r.status(500).json({error:e.message});}};
const create = async(q,r)=>{try{const item=normalize(q.body),error=validate(item);if(error)return r.status(400).json({error});r.status(201).json(shape(await coilModel.create(item)));}catch(e){r.status(500).json({error:e.message});}};
const importRows = async(q,r)=>{try{if(!Array.isArray(q.body)||!q.body.length)return r.status(400).json({error:"At least one coil row is required."});if(q.body.length>1000)return r.status(400).json({error:"A maximum of 1,000 rows can be imported at once."});const items=q.body.map(normalize),bad=items.findIndex(item=>validate(item));if(bad>=0)return r.status(400).json({error:`Row ${bad+2}: ${validate(items[bad])}`});await coilModel.createMany(items);r.status(201).json({imported:items.length});}catch(e){r.status(500).json({error:e.message});}};
const update = async(q,r)=>{try{const item=normalize(q.body),error=validate(item);if(error)return r.status(400).json({error});const row=await coilModel.update(q.params.id,item);if(!row)return r.status(404).json({error:"Coil not found."});r.json(shape(row));}catch(e){r.status(500).json({error:e.message});}};
const remove = async(q,r)=>{try{const row=await coilModel.remove(q.params.id);if(!row)return r.status(404).json({error:"Coil not found."});r.json({message:"Coil deleted."});}catch(e){r.status(500).json({error:e.message});}};
module.exports={list,get,create,importRows,update,remove};
