import React,{useCallback,useEffect,useState}from'react';
import{Button,Card,CardContent,Chip,Dialog,DialogActions,DialogContent,DialogTitle,Grid,IconButton,InputAdornment,MenuItem,Snackbar,Table,TableBody,TableCell,TableContainer,TableHead,TableRow,TextField,Tooltip,Typography}from'@material-ui/core';
import{Add,Delete,Edit,Print,Refresh,Search}from'@material-ui/icons';import{Alert}from'@material-ui/lab';import axios from'axios';import moment from'moment';import EmployeeAvatar from'../common/EmployeeAvatar';import SalesOrderImportButton from'./SalesOrderImportButton';
const DELIVERY_STATUSES=['Pending','Ready for Dispatch','Loading','Out for Delivery','Delivered','Failed Delivery','Cancelled'];
const PICKUP_STATUSES=['Pending','Ready for Dispatch','Loading','Released','Cancelled'];
const blankItem={ItemDescription:'',Specification:'',Quantity:'',Unit:'pcs',LoadedQuantity:'',DeliveredQuantity:'',Notes:''};
const makeNo=()=>`DSP-${moment().format('YYYYMMDD-HHmm')}`;
const blank=()=>({DispatchNo:makeNo(),OrderReference:'',ProductionBatchNo:'',CustomerName:'',ContactPerson:'',ContactNo:'',FulfillmentType:'Customer Pickup',DeliveryAddress:'',ScheduledDate:'',VehicleId:'',DriverEmployeeId:'',HelperNames:'',DeliveryFee:0,FeeStatus:'Unbilled',Status:'Pending',SpecialInstructions:'',LoadingCheckedBy:'',ReleasedBy:'',ReceivedBy:'',DeliveredAt:'',ProofOfDelivery:'',CustomerSignature:'',FailureReason:'',Items:[{...blankItem}]});
const money=v=>`₱${Number(v||0).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})}`;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export default function DispatchOrders(){
 const[rows,setRows]=useState([]),[vehicles,setVehicles]=useState([]),[employees,setEmployees]=useState([]),[batches,setBatches]=useState([]),[search,setSearch]=useState(''),[statusFilter,setStatusFilter]=useState(''),[typeFilter,setTypeFilter]=useState(''),[form,setForm]=useState(blank()),[editing,setEditing]=useState(null),[open,setOpen]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(null);
 const endpoint=window.apihost+'dispatch/orders';
 const load=useCallback(()=>{const q=new URLSearchParams();if(search.trim())q.set('search',search.trim());if(statusFilter)q.set('status',statusFilter);if(typeFilter)q.set('fulfillmentType',typeFilter);axios.get(`${endpoint}?${q}`).then(r=>setRows(r.data||[])).catch(e=>setMessage({type:'error',text:e.response?.data?.message||'Unable to load dispatch orders.'}))},[endpoint,search,statusFilter,typeFilter]);
 const loadOptions=useCallback(()=>{axios.get(window.apihost+'dispatch/vehicles').then(r=>setVehicles(r.data||[])).catch(()=>{});axios.get(window.apihost+'employees/options').then(r=>setEmployees(r.data||[])).catch(()=>{});axios.get(window.apihost+'dispatch/options/released-batches').then(r=>setBatches(r.data||[])).catch(()=>{})},[]);
 useEffect(load,[load]);useEffect(loadOptions,[loadOptions]);
 const show=row=>{setEditing(row||null);setForm(row?{...blank(),...row,ScheduledDate:row.ScheduledDate?moment(row.ScheduledDate).format('YYYY-MM-DDTHH:mm'):'',DeliveredAt:row.DeliveredAt?moment(row.DeliveredAt).format('YYYY-MM-DDTHH:mm'):'',VehicleId:row.VehicleId||'',DriverEmployeeId:row.DriverEmployeeId||'',Items:(row.Items||[]).map(i=>({...i}))}:{...blank()});setOpen(true)};
 const set=(name,value)=>setForm(current=>({...current,[name]:value}));const setItem=(index,name,value)=>setForm(current=>({...current,Items:current.Items.map((item,i)=>i===index?{...item,[name]:value}:item)}));
 const addItem=()=>setForm(current=>({...current,Items:[...current.Items,{...blankItem}]}));const removeItem=index=>setForm(current=>({...current,Items:current.Items.filter((_x,i)=>i!==index)}));
 const image=(name,file)=>{if(!file)return;if(file.size>2500000){setMessage({type:'error',text:'Image must be 2.5 MB or smaller.'});return}const reader=new FileReader();reader.onload=()=>set(name,reader.result);reader.readAsDataURL(file)};
 const save=async e=>{e.preventDefault();setBusy(true);try{editing?await axios.put(`${endpoint}/${editing.Id}`,form):await axios.post(endpoint,form);setOpen(false);setMessage({type:'success',text:'Dispatch order saved.'});load();loadOptions()}catch(error){setMessage({type:'error',text:error.response?.data?.message||'Unable to save dispatch.'})}finally{setBusy(false)}};
 const remove=async row=>{if(!window.confirm(`Cancel dispatch ${row.DispatchNo}?`))return;try{await axios.delete(`${endpoint}/${row.Id}`);load();loadOptions()}catch(e){setMessage({type:'error',text:e.response?.data?.message||'Unable to cancel dispatch.'})}};
 const print=row=>{const win=window.open('','_blank','width=900,height=760');if(!win)return;const items=(row.Items||[]).map(i=>`<tr><td>${esc(i.ItemDescription)}</td><td>${esc(i.Specification)}</td><td>${esc(i.Quantity)}</td><td>${esc(i.Unit)}</td><td>${esc(i.LoadedQuantity||'')}</td><td>${esc(i.DeliveredQuantity||'')}</td></tr>`).join('');win.document.write(`<!doctype html><html><head><title>${esc(row.DispatchNo)}</title><style>body{font:14px Arial;padding:32px;color:#111}h1{margin:0}small{color:#555}.grid{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin:24px 0}table{width:100%;border-collapse:collapse}th,td{border:1px solid #bbb;padding:8px;text-align:left}.sign{display:grid;grid-template-columns:1fr 1fr;gap:50px;margin-top:70px}.line{border-top:1px solid #222;text-align:center;padding-top:7px}@media print{button{display:none}}</style></head><body><h1>Dispatch & Delivery Receipt</h1><small>Unimore Trading</small><div class="grid"><div><b>Dispatch No.:</b> ${esc(row.DispatchNo)}</div><div><b>Schedule:</b> ${row.ScheduledDate?esc(moment(row.ScheduledDate).format('MMM D, YYYY h:mm A')):'—'}</div><div><b>Customer:</b> ${esc(row.CustomerName)}</div><div><b>Order Ref.:</b> ${esc(row.OrderReference||'—')}</div><div><b>Fulfillment:</b> ${esc(row.FulfillmentType)}</div><div><b>Status:</b> ${esc(row.Status)}</div><div><b>Address:</b> ${esc(row.DeliveryAddress||'—')}</div><div><b>Vehicle / Driver:</b> ${esc([row.PlateNo,row.DriverName].filter(Boolean).join(' / ')||'—')}</div></div><table><thead><tr><th>Item</th><th>Specification</th><th>Ordered</th><th>Unit</th><th>Loaded</th><th>Delivered</th></tr></thead><tbody>${items}</tbody></table><p><b>Delivery Fee:</b> ${money(row.DeliveryFee)}</p><p><b>Instructions:</b> ${esc(row.SpecialInstructions||'None')}</p><div class="sign"><div class="line">Released By: ${esc(row.ReleasedBy||'')}</div><div class="line">Received By: ${esc(row.ReceivedBy||'')}</div></div><button onclick="window.print()">Print</button></body></html>`);win.document.close()};
 const statuses=form.FulfillmentType==='Company Delivery'?DELIVERY_STATUSES:PICKUP_STATUSES;
 const field=(name,label,props={})=><TextField fullWidth margin="dense" variant="outlined" label={label} value={form[name]} onChange={e=>set(name,e.target.value)} {...props}/>;
 return <div><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:16,flexWrap:'wrap',marginBottom:16}}><div><Typography variant="h5" style={{fontWeight:700}}>Dispatch Orders</Typography><Typography color="textSecondary">Control customer pickup, loading and company-truck delivery.</Typography></div><div><Tooltip title="Refresh"><IconButton onClick={()=>{load();loadOptions()}}><Refresh/></IconButton></Tooltip><SalesOrderImportButton onImported={()=>{load();loadOptions()}}/><Button variant="contained" color="primary" startIcon={<Add/>} onClick={()=>show(null)}>New Dispatch</Button></div></div>
 <Card style={{marginBottom:16}}><CardContent><Grid container spacing={2}><Grid item xs={12} md={6}><TextField fullWidth size="small" variant="outlined" placeholder="Search dispatch, order, customer or batch" value={search} onChange={e=>setSearch(e.target.value)} InputProps={{startAdornment:<InputAdornment position="start"><Search/></InputAdornment>}}/></Grid><Grid item xs={12} sm={6} md={3}><TextField select fullWidth size="small" variant="outlined" label="Fulfillment" value={typeFilter} onChange={e=>setTypeFilter(e.target.value)}><MenuItem value="">All</MenuItem><MenuItem value="Customer Pickup">Customer Pickup</MenuItem><MenuItem value="Company Delivery">Company Delivery</MenuItem></TextField></Grid><Grid item xs={12} sm={6} md={3}><TextField select fullWidth size="small" variant="outlined" label="Status" value={statusFilter} onChange={e=>setStatusFilter(e.target.value)}><MenuItem value="">All</MenuItem>{Array.from(new Set([...DELIVERY_STATUSES,...PICKUP_STATUSES])).map(x=><MenuItem key={x} value={x}>{x}</MenuItem>)}</TextField></Grid></Grid></CardContent></Card>
 <Card><CardContent style={{padding:0}}><TableContainer style={{maxHeight:'calc(100vh - 260px)'}}><Table stickyHeader size="small"><TableHead><TableRow>{['Dispatch','Customer','Fulfillment','Schedule','Items','Truck / Driver','Delivery Fee','Status','Actions'].map(h=><TableCell key={h} style={{fontWeight:700,whiteSpace:'nowrap'}}>{h}</TableCell>)}</TableRow></TableHead><TableBody>{!rows.length&&<TableRow><TableCell colSpan={9} align="center" style={{padding:40}}>No dispatch records found.</TableCell></TableRow>}{rows.map(r=><TableRow hover key={r.Id}><TableCell><b>{r.DispatchNo}</b><br/><Typography variant="caption" color="textSecondary">{r.OrderReference||r.ProductionBatchNo||''}</Typography></TableCell><TableCell>{r.CustomerName}<br/><Typography variant="caption" color="textSecondary">{r.ContactPerson||''}</Typography></TableCell><TableCell>{r.FulfillmentType}</TableCell><TableCell style={{whiteSpace:'nowrap'}}>{r.ScheduledDate?moment(r.ScheduledDate).format('MMM D, h:mm A'):'—'}</TableCell><TableCell>{r.Items?.length||0}</TableCell><TableCell>{r.DriverName?<div style={{display:'flex',gap:7,alignItems:'center'}}><EmployeeAvatar image={r.DriverImage} name={r.DriverName} size={28}/><span>{r.PlateNo}<br/>{r.DriverName}</span></div>:'—'}</TableCell><TableCell>{money(r.DeliveryFee)}<br/><Typography variant="caption" color="textSecondary">{r.FeeStatus}</Typography></TableCell><TableCell><Chip size="small" label={r.Status} color={r.Status==='Delivered'||r.Status==='Released'?'primary':r.Status==='Failed Delivery'?'secondary':'default'}/></TableCell><TableCell style={{whiteSpace:'nowrap'}}><IconButton size="small" onClick={()=>print(r)}><Print fontSize="small"/></IconButton><IconButton size="small" onClick={()=>show(r)}><Edit fontSize="small"/></IconButton><IconButton size="small" onClick={()=>remove(r)}><Delete fontSize="small"/></IconButton></TableCell></TableRow>)}</TableBody></Table></TableContainer></CardContent></Card>
 <Dialog open={open} onClose={()=>!busy&&setOpen(false)} fullWidth maxWidth="lg"><form onSubmit={save}><DialogTitle>{editing?'Edit':'Create'} Dispatch Order</DialogTitle><DialogContent><Typography variant="subtitle1" style={{fontWeight:700,marginTop:4}}>Customer & Order</Typography><Grid container spacing={2}><Grid item xs={12} sm={4}>{field('DispatchNo','Dispatch No.',{required:true})}</Grid><Grid item xs={12} sm={4}>{field('OrderReference','Customer Order Reference')}</Grid><Grid item xs={12} sm={4}>{field('ProductionBatchNo','Released Production Batch',{select:true,children:[<MenuItem key="none" value="">No linked batch</MenuItem>,...batches.map(b=><MenuItem key={b.Id} value={b.BatchNo}>{b.BatchNo} — {b.FinishedProduct}</MenuItem>)]})}</Grid><Grid item xs={12} sm={4}>{field('CustomerName','Customer Name',{required:true})}</Grid><Grid item xs={12} sm={4}>{field('ContactPerson','Contact Person')}</Grid><Grid item xs={12} sm={4}>{field('ContactNo','Contact Number')}</Grid></Grid>
 <Typography variant="subtitle1" style={{fontWeight:700,marginTop:16}}>Fulfillment & Schedule</Typography><Grid container spacing={2}><Grid item xs={12} sm={4}>{field('FulfillmentType','Fulfillment Method',{select:true,required:true,children:['Customer Pickup','Company Delivery'].map(x=><MenuItem key={x} value={x}>{x}</MenuItem>)})}</Grid><Grid item xs={12} sm={4}>{field('ScheduledDate','Scheduled Date / Time',{type:'datetime-local',InputLabelProps:{shrink:true}})}</Grid><Grid item xs={12} sm={4}>{field('Status','Dispatch Status',{select:true,children:statuses.map(x=><MenuItem key={x} value={x}>{x}</MenuItem>)})}</Grid>{form.FulfillmentType==='Company Delivery'&&<><Grid item xs={12}>{field('DeliveryAddress','Delivery Address',{required:true,multiline:true,rows:2})}</Grid><Grid item xs={12} sm={4}>{field('VehicleId','Assigned Vehicle',{select:true,children:[<MenuItem key="none" value="">Unassigned</MenuItem>,...vehicles.filter(v=>['Available','In Use'].includes(v.Status)||v.Id===Number(form.VehicleId)).map(v=><MenuItem key={v.Id} value={v.Id}>{v.PlateNo} — {v.VehicleName||v.MakeModel}</MenuItem>)]})}</Grid><Grid item xs={12} sm={4}>{field('DriverEmployeeId','Driver',{select:true,children:[<MenuItem key="none" value="">Unassigned</MenuItem>,...employees.map(e=><MenuItem key={e.id} value={e.id}>{e.employeeNo} — {e.employeeName}</MenuItem>)]})}</Grid><Grid item xs={12} sm={4}>{field('HelperNames','Helpers / Loaders')}</Grid><Grid item xs={12} sm={4}>{field('DeliveryFee','Delivery Fee',{type:'number',inputProps:{min:0,step:'.01'}})}</Grid><Grid item xs={12} sm={4}>{field('FeeStatus','Fee Status',{select:true,children:['Unbilled','Billed','Paid','Waived'].map(x=><MenuItem key={x} value={x}>{x}</MenuItem>)})}</Grid></>}</Grid>
 <Typography variant="subtitle1" style={{fontWeight:700,marginTop:16}}>Dispatch Items</Typography>{form.Items.map((item,index)=><Card key={index} variant="outlined" style={{marginBottom:10}}><CardContent><Grid container spacing={1}><Grid item xs={12} sm={4}><TextField fullWidth size="small" variant="outlined" required label="Item Description" value={item.ItemDescription} onChange={e=>setItem(index,'ItemDescription',e.target.value)}/></Grid><Grid item xs={12} sm={3}><TextField fullWidth size="small" variant="outlined" label="Specification" value={item.Specification} onChange={e=>setItem(index,'Specification',e.target.value)}/></Grid><Grid item xs={6} sm={1}><TextField fullWidth size="small" type="number" variant="outlined" required label="Qty" value={item.Quantity} onChange={e=>setItem(index,'Quantity',e.target.value)}/></Grid><Grid item xs={6} sm={1}><TextField fullWidth size="small" variant="outlined" label="Unit" value={item.Unit} onChange={e=>setItem(index,'Unit',e.target.value)}/></Grid><Grid item xs={6} sm={1}><TextField fullWidth size="small" type="number" variant="outlined" label="Loaded" value={item.LoadedQuantity} onChange={e=>setItem(index,'LoadedQuantity',e.target.value)}/></Grid><Grid item xs={6} sm={1}><TextField fullWidth size="small" type="number" variant="outlined" label="Delivered" value={item.DeliveredQuantity} onChange={e=>setItem(index,'DeliveredQuantity',e.target.value)}/></Grid><Grid item xs={12} sm={1}><IconButton color="secondary" disabled={form.Items.length===1} onClick={()=>removeItem(index)}><Delete/></IconButton></Grid></Grid></CardContent></Card>)}<Button startIcon={<Add/>} onClick={addItem}>Add Item</Button>
 <Typography variant="subtitle1" style={{fontWeight:700,marginTop:16}}>Release & Completion</Typography><Grid container spacing={2}><Grid item xs={12} sm={4}>{field('LoadingCheckedBy','Loading Checked By')}</Grid><Grid item xs={12} sm={4}>{field('ReleasedBy','Released By')}</Grid><Grid item xs={12} sm={4}>{field('ReceivedBy','Received By')}</Grid><Grid item xs={12} sm={4}>{field('DeliveredAt','Delivered / Released At',{type:'datetime-local',InputLabelProps:{shrink:true}})}</Grid><Grid item xs={12} sm={8}>{field('SpecialInstructions','Special Instructions',{multiline:true,rows:2})}</Grid>{form.Status==='Failed Delivery'&&<Grid item xs={12}>{field('FailureReason','Failure Reason',{required:true,multiline:true,rows:2})}</Grid>}
 {form.FulfillmentType==='Company Delivery'&&<><Grid item xs={12} sm={6}><div style={{border:'1px solid var(--app-border)',borderRadius:8,padding:12}}><Typography variant="body2" style={{fontWeight:700}}>Proof of Delivery Photo</Typography><input type="file" accept="image/*" onChange={e=>image('ProofOfDelivery',e.target.files[0])}/>{form.ProofOfDelivery&&<div><img src={form.ProofOfDelivery} alt="Proof of delivery" style={{width:120,height:85,objectFit:'cover',marginTop:8,borderRadius:6}}/><Button size="small" color="secondary" onClick={()=>set('ProofOfDelivery','')}>Remove</Button></div>}</div></Grid><Grid item xs={12} sm={6}><div style={{border:'1px solid var(--app-border)',borderRadius:8,padding:12}}><Typography variant="body2" style={{fontWeight:700}}>Customer Signature / Signed DR</Typography><input type="file" accept="image/*" onChange={e=>image('CustomerSignature',e.target.files[0])}/>{form.CustomerSignature&&<div><img src={form.CustomerSignature} alt="Customer signature" style={{width:120,height:85,objectFit:'contain',marginTop:8,borderRadius:6}}/><Button size="small" color="secondary" onClick={()=>set('CustomerSignature','')}>Remove</Button></div>}</div></Grid></>}</Grid>
 </DialogContent><DialogActions><Button onClick={()=>setOpen(false)} disabled={busy}>Cancel</Button><Button type="submit" variant="contained" color="primary" disabled={busy}>{busy?'Saving…':'Save Dispatch'}</Button></DialogActions></form></Dialog><Snackbar open={Boolean(message)} autoHideDuration={6000} onClose={()=>setMessage(null)}><Alert severity={message?.type||'info'} onClose={()=>setMessage(null)}>{message?.text}</Alert></Snackbar></div>
}
