const fs=require('fs');const path=require('path');const{getPool,sql}=require('../config/db');
let schemaReady=false;
const ensureSchema=async()=>{if(schemaReady)return;await getPool().request().batch(fs.readFileSync(path.join(__dirname,'..','database','dispatch_schema.sql'),'utf8'));schemaReady=true;};
const orderFields={DispatchNo:sql.NVarChar(60),OrderReference:sql.NVarChar(100),ProductionBatchNo:sql.NVarChar(60),CustomerName:sql.NVarChar(180),ContactPerson:sql.NVarChar(150),ContactNo:sql.NVarChar(80),FulfillmentType:sql.NVarChar(40),DeliveryAddress:sql.NVarChar(500),ScheduledDate:sql.DateTime2,VehicleId:sql.Int,DriverEmployeeId:sql.Int,HelperNames:sql.NVarChar(300),DeliveryFee:sql.Decimal(18,2),FeeStatus:sql.NVarChar(30),Status:sql.NVarChar(40),SpecialInstructions:sql.NVarChar(700),LoadingCheckedBy:sql.NVarChar(150),ReleasedBy:sql.NVarChar(150),ReceivedBy:sql.NVarChar(150),DeliveredAt:sql.DateTime2,ProofOfDelivery:sql.NVarChar(sql.MAX),CustomerSignature:sql.NVarChar(sql.MAX),FailureReason:sql.NVarChar(700)};
const vehicleFields={PlateNo:sql.NVarChar(40),VehicleName:sql.NVarChar(120),VehicleType:sql.NVarChar(60),Capacity:sql.NVarChar(80),MakeModel:sql.NVarChar(150),RegistrationExpiry:sql.Date,Status:sql.NVarChar(30),Notes:sql.NVarChar(700)};
const value=v=>v===''||v===undefined?null:v;
const bind=(request,fields,data)=>{Object.entries(fields).forEach(([name,type])=>request.input(name,type,value(data[name])));return request;};
const validateBatch=async batchNo=>{if(!batchNo)return;const row=(await getPool().request().input('BatchNo',sql.NVarChar(60),batchNo).query('SELECT TOP 1 BatchNo,QAStatus FROM ProductionTraceability WHERE BatchNo=@BatchNo')).recordset[0];if(!row){const e=new Error('Production batch was not found.');e.status=400;throw e;}if(row.QAStatus!=='Released'){const e=new Error(`Production batch ${batchNo} is not released by Quality Assurance.`);e.status=409;throw e;}};
const listOrders=async filters=>{await ensureSchema();const request=getPool().request(),clauses=['o.IsDeleted=0'];
 if(filters.status){request.input('StatusFilter',sql.NVarChar(40),filters.status);clauses.push('o.Status=@StatusFilter');}
 if(filters.fulfillmentType){request.input('FulfillmentTypeFilter',sql.NVarChar(40),filters.fulfillmentType);clauses.push('o.FulfillmentType=@FulfillmentTypeFilter');}
 if(filters.search){request.input('Search',sql.NVarChar(220),`%${filters.search}%`);clauses.push('(o.DispatchNo LIKE @Search OR o.OrderReference LIKE @Search OR o.CustomerName LIKE @Search OR o.ProductionBatchNo LIKE @Search OR o.DeliveryAddress LIKE @Search)');}
 const result=await request.query(`SELECT o.*,v.PlateNo,v.VehicleName,CONCAT(e.FirstName,' ',ISNULL(e.MiddleName,''),' ',e.LastName) DriverName,e.EmployeeNo DriverEmployeeNo,e.Image DriverImage
 FROM DispatchOrders o LEFT JOIN FleetVehicles v ON v.Id=o.VehicleId LEFT JOIN Employees e ON e.Id=o.DriverEmployeeId WHERE ${clauses.join(' AND ')} ORDER BY CASE WHEN o.Status IN ('Delivered','Completed','Cancelled') THEN 1 ELSE 0 END,o.ScheduledDate,o.Id DESC;
 SELECT i.* FROM DispatchItems i INNER JOIN DispatchOrders o ON o.Id=i.DispatchOrderId WHERE ${clauses.join(' AND ')} ORDER BY i.Id;`);
 const itemsByOrder=result.recordsets[1].reduce((a,item)=>({...a,[item.DispatchOrderId]:[...(a[item.DispatchOrderId]||[]),item]}),{});
 return result.recordsets[0].map(order=>({...order,Items:itemsByOrder[order.Id]||[]}));};
const findOrder=async id=>{const rows=await listOrders({});return rows.find(row=>row.Id===Number(id))||null;};
const saveItems=async(transaction,orderId,items,replace=false)=>{if(replace)await new sql.Request(transaction).input('OrderId',sql.Int,orderId).query('DELETE FROM DispatchItems WHERE DispatchOrderId=@OrderId');for(const item of items){await new sql.Request(transaction).input('OrderId',sql.Int,orderId).input('ItemDescription',sql.NVarChar(250),item.ItemDescription).input('Specification',sql.NVarChar(250),value(item.Specification)).input('Quantity',sql.Decimal(18,3),item.Quantity).input('Unit',sql.NVarChar(40),value(item.Unit)).input('LoadedQuantity',sql.Decimal(18,3),value(item.LoadedQuantity)).input('DeliveredQuantity',sql.Decimal(18,3),value(item.DeliveredQuantity)).input('Notes',sql.NVarChar(500),value(item.Notes)).query(`INSERT INTO DispatchItems(DispatchOrderId,ItemDescription,Specification,Quantity,Unit,LoadedQuantity,DeliveredQuantity,Notes) VALUES(@OrderId,@ItemDescription,@Specification,@Quantity,@Unit,@LoadedQuantity,@DeliveredQuantity,@Notes)`);}};
const normalizeOrder=data=>({...data,DeliveryFee:data.FulfillmentType==='Customer Pickup'?0:Number(data.DeliveryFee||0),VehicleId:data.FulfillmentType==='Customer Pickup'?null:value(data.VehicleId),DriverEmployeeId:data.FulfillmentType==='Customer Pickup'?null:value(data.DriverEmployeeId),FeeStatus:data.FeeStatus||'Unbilled',Status:data.Status||'Pending'});
const createOrder=async(data,userId)=>{await ensureSchema();data=normalizeOrder(data);await validateBatch(data.ProductionBatchNo);if(!data.DispatchNo||!data.CustomerName||!data.FulfillmentType){const e=new Error('Dispatch number, customer and fulfillment type are required.');e.status=400;throw e;}if(!Array.isArray(data.Items)||!data.Items.length){const e=new Error('Add at least one dispatch item.');e.status=400;throw e;}const transaction=new sql.Transaction(getPool());await transaction.begin();try{const request=bind(new sql.Request(transaction),orderFields,data).input('CreatedBy',sql.Int,userId||null);const names=Object.keys(orderFields);const row=(await request.query(`INSERT INTO DispatchOrders(${names.map(n=>`[${n}]`).join(',')},CreatedBy) OUTPUT INSERTED.* VALUES(${names.map(n=>'@'+n).join(',')},@CreatedBy)`)).recordset[0];await saveItems(transaction,row.Id,data.Items);await transaction.commit();return row;}catch(e){await transaction.rollback();throw e;}};
const setVehicleOperationalStatus=async(transaction,vehicleId,status)=>{if(!vehicleId)return;await new sql.Request(transaction).input('Id',sql.Int,vehicleId).input('Status',sql.NVarChar(30),status).query('UPDATE FleetVehicles SET Status=@Status,UpdatedAt=SYSUTCDATETIME() WHERE Id=@Id AND IsDeleted=0');};
const updateOrder=async(id,data)=>{await ensureSchema();const old=await findOrder(id);if(!old)return null;data=normalizeOrder(data);if(['Delivered','Released'].includes(data.Status)&&!data.DeliveredAt)data.DeliveredAt=new Date();await validateBatch(data.ProductionBatchNo);if(!Array.isArray(data.Items)||!data.Items.length){const e=new Error('Add at least one dispatch item.');e.status=400;throw e;}if(data.Status==='Out for Delivery'&&data.FulfillmentType==='Company Delivery'&&(!data.VehicleId||!data.DriverEmployeeId)){const e=new Error('Assign a vehicle and driver before dispatching the delivery.');e.status=400;throw e;}if(data.Status==='Delivered'&&data.FulfillmentType==='Company Delivery'&&(!data.ReceivedBy||!data.ProofOfDelivery)){const e=new Error('Received-by name and proof-of-delivery photo are required before marking delivered.');e.status=400;throw e;}if(data.Status==='Released'&&data.FulfillmentType==='Customer Pickup'&&!data.ReceivedBy){const e=new Error('Enter the person who received the customer pickup.');e.status=400;throw e;}if(data.Status==='Failed Delivery'&&!data.FailureReason){const e=new Error('Enter a reason for the failed delivery.');e.status=400;throw e;}const transaction=new sql.Transaction(getPool());await transaction.begin();try{if(data.Status==='Out for Delivery'&&data.VehicleId){const vehicle=(await new sql.Request(transaction).input('Id',sql.Int,data.VehicleId).query('SELECT Status FROM FleetVehicles WHERE Id=@Id AND IsDeleted=0')).recordset[0];if(!vehicle||(!['Available','In Use'].includes(vehicle.Status))){const e=new Error('Selected vehicle is not available for dispatch.');e.status=409;throw e;}}const request=bind(new sql.Request(transaction),orderFields,data).input('Id',sql.Int,id);const names=Object.keys(orderFields);const row=(await request.query(`UPDATE DispatchOrders SET ${names.map(n=>`[${n}]=@${n}`).join(',')},UpdatedAt=SYSUTCDATETIME() OUTPUT INSERTED.* WHERE Id=@Id AND IsDeleted=0`)).recordset[0];await saveItems(transaction,id,data.Items,true);if(old.VehicleId&&old.VehicleId!==row.VehicleId)await setVehicleOperationalStatus(transaction,old.VehicleId,'Available');if(row.FulfillmentType==='Company Delivery'&&row.VehicleId){if(row.Status==='Out for Delivery')await setVehicleOperationalStatus(transaction,row.VehicleId,'In Use');else if(['Delivered','Failed Delivery','Cancelled'].includes(row.Status))await setVehicleOperationalStatus(transaction,row.VehicleId,'Available');}await transaction.commit();return row;}catch(e){await transaction.rollback();throw e;}};
const removeOrder=async id=>{await ensureSchema();const old=await findOrder(id);if(!old)return null;await getPool().request().input('Id',sql.Int,id).query('UPDATE DispatchOrders SET IsDeleted=1,Status=\'Cancelled\',UpdatedAt=SYSUTCDATETIME() WHERE Id=@Id');if(old.VehicleId)await getPool().request().input('Id',sql.Int,old.VehicleId).query("UPDATE FleetVehicles SET Status='Available',UpdatedAt=SYSUTCDATETIME() WHERE Id=@Id AND Status='In Use'");return old;};
const listVehicles=async()=>{await ensureSchema();return(await getPool().request().query('SELECT * FROM FleetVehicles WHERE IsDeleted=0 ORDER BY PlateNo')).recordset;};
const findVehicle=async id=>{await ensureSchema();return(await getPool().request().input('Id',sql.Int,id).query('SELECT * FROM FleetVehicles WHERE Id=@Id AND IsDeleted=0')).recordset[0]||null;};
const createVehicle=async(data,userId)=>{await ensureSchema();data={Status:'Available',...data};if(!data.PlateNo){const e=new Error('Plate number is required.');e.status=400;throw e;}const request=bind(getPool().request(),vehicleFields,data).input('CreatedBy',sql.Int,userId||null),names=Object.keys(vehicleFields);return(await request.query(`INSERT INTO FleetVehicles(${names.map(n=>`[${n}]`).join(',')},CreatedBy) OUTPUT INSERTED.* VALUES(${names.map(n=>'@'+n).join(',')},@CreatedBy)`)).recordset[0];};
const updateVehicle=async(id,data)=>{await ensureSchema();const request=bind(getPool().request(),vehicleFields,data).input('Id',sql.Int,id),names=Object.keys(vehicleFields);return(await request.query(`UPDATE FleetVehicles SET ${names.map(n=>`[${n}]=@${n}`).join(',')},UpdatedAt=SYSUTCDATETIME() OUTPUT INSERTED.* WHERE Id=@Id AND IsDeleted=0`)).recordset[0]||null;};
const removeVehicle=async id=>{await ensureSchema();const usage=(await getPool().request().input('Id',sql.Int,id).query("SELECT COUNT(*) total FROM DispatchOrders WHERE VehicleId=@Id AND IsDeleted=0 AND Status NOT IN ('Delivered','Completed','Cancelled','Failed Delivery')")).recordset[0].total;if(usage){const e=new Error('Vehicle is assigned to an active dispatch.');e.status=409;throw e;}return(await getPool().request().input('Id',sql.Int,id).query('UPDATE FleetVehicles SET IsDeleted=1,UpdatedAt=SYSUTCDATETIME() OUTPUT INSERTED.* WHERE Id=@Id AND IsDeleted=0')).recordset[0]||null;};
const releasedBatches=async()=>{await ensureSchema();return(await getPool().request().query("SELECT Id,BatchNo,FinishedProduct,Quantity,ProductionDate FROM ProductionTraceability WHERE QAStatus='Released' ORDER BY ProductionDate DESC,Id DESC")).recordset;};
const dashboard=async()=>{await ensureSchema();const r=await getPool().request().query(`SELECT COUNT(*) TotalOrders,SUM(CASE WHEN Status='Ready for Dispatch' THEN 1 ELSE 0 END) Ready,SUM(CASE WHEN Status='Out for Delivery' THEN 1 ELSE 0 END) InTransit,SUM(CASE WHEN Status='Delivered' THEN 1 ELSE 0 END) Delivered,SUM(CASE WHEN Status='Failed Delivery' THEN 1 ELSE 0 END) Failed,SUM(CASE WHEN Status='Delivered' AND FeeStatus IN ('Unbilled','Billed') THEN DeliveryFee ELSE 0 END) OutstandingDeliveryFees FROM DispatchOrders WHERE IsDeleted=0;SELECT COUNT(*) AvailableVehicles FROM FleetVehicles WHERE IsDeleted=0 AND Status='Available';SELECT TOP 10 o.Id,o.DispatchNo,o.CustomerName,o.FulfillmentType,o.ScheduledDate,o.Status,o.DeliveryFee,v.PlateNo,CONCAT(e.FirstName,' ',e.LastName) DriverName FROM DispatchOrders o LEFT JOIN FleetVehicles v ON v.Id=o.VehicleId LEFT JOIN Employees e ON e.Id=o.DriverEmployeeId WHERE o.IsDeleted=0 AND o.Status NOT IN ('Delivered','Released','Cancelled') ORDER BY o.ScheduledDate,o.Id;`);return{summary:r.recordsets[0][0],availableVehicles:r.recordsets[1][0].AvailableVehicles||0,upcoming:r.recordsets[2]};};
module.exports={ensureSchema,listOrders,findOrder,createOrder,updateOrder,removeOrder,listVehicles,findVehicle,createVehicle,updateVehicle,removeVehicle,releasedBatches,dashboard};
